// Code generated by mockery v2.53.0. DO NOT EDIT.

package usecase

import (
	model "github.com/mattermost/mattermost/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// MockChannelRepo is an autogenerated mock type for the ChannelRepo type
type MockChannelRepo struct {
	mock.Mock
}

type MockChannelRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChannelRepo) EXPECT() *MockChannelRepo_Expecter {
	return &MockChannelRepo_Expecter{mock: &_m.Mock}
}

// AddMemberByUserID provides a mock function with given fields: channelID, userID
func (_m *MockChannelRepo) AddMemberByUserID(channelID string, userID string) (*model.ChannelMember, *model.AppError) {
	ret := _m.Called(channelID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddMemberByUserID")
	}

	var r0 *model.ChannelMember
	var r1 *model.AppError
	if rf, ok := ret.Get(0).(func(string, string) (*model.ChannelMember, *model.AppError)); ok {
		return rf(channelID, userID)
	}
	if rf, ok := ret.Get(0).(func(string, string) *model.ChannelMember); ok {
		r0 = rf(channelID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ChannelMember)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) *model.AppError); ok {
		r1 = rf(channelID, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.AppError)
		}
	}

	return r0, r1
}

// MockChannelRepo_AddMemberByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMemberByUserID'
type MockChannelRepo_AddMemberByUserID_Call struct {
	*mock.Call
}

// AddMemberByUserID is a helper method to define mock.On call
//   - channelID string
//   - userID string
func (_e *MockChannelRepo_Expecter) AddMemberByUserID(channelID interface{}, userID interface{}) *MockChannelRepo_AddMemberByUserID_Call {
	return &MockChannelRepo_AddMemberByUserID_Call{Call: _e.mock.On("AddMemberByUserID", channelID, userID)}
}

func (_c *MockChannelRepo_AddMemberByUserID_Call) Run(run func(channelID string, userID string)) *MockChannelRepo_AddMemberByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockChannelRepo_AddMemberByUserID_Call) Return(_a0 *model.ChannelMember, _a1 *model.AppError) *MockChannelRepo_AddMemberByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChannelRepo_AddMemberByUserID_Call) RunAndReturn(run func(string, string) (*model.ChannelMember, *model.AppError)) *MockChannelRepo_AddMemberByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: channelID
func (_m *MockChannelRepo) Get(channelID string) (*model.Channel, *model.AppError) {
	ret := _m.Called(channelID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Channel
	var r1 *model.AppError
	if rf, ok := ret.Get(0).(func(string) (*model.Channel, *model.AppError)); ok {
		return rf(channelID)
	}
	if rf, ok := ret.Get(0).(func(string) *model.Channel); ok {
		r0 = rf(channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *model.AppError); ok {
		r1 = rf(channelID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.AppError)
		}
	}

	return r0, r1
}

// MockChannelRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockChannelRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - channelID string
func (_e *MockChannelRepo_Expecter) Get(channelID interface{}) *MockChannelRepo_Get_Call {
	return &MockChannelRepo_Get_Call{Call: _e.mock.On("Get", channelID)}
}

func (_c *MockChannelRepo_Get_Call) Run(run func(channelID string)) *MockChannelRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockChannelRepo_Get_Call) Return(_a0 *model.Channel, _a1 *model.AppError) *MockChannelRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChannelRepo_Get_Call) RunAndReturn(run func(string) (*model.Channel, *model.AppError)) *MockChannelRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: teamID, channelName
func (_m *MockChannelRepo) GetByName(teamID string, channelName string) (*model.Channel, *model.AppError) {
	ret := _m.Called(teamID, channelName)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *model.Channel
	var r1 *model.AppError
	if rf, ok := ret.Get(0).(func(string, string) (*model.Channel, *model.AppError)); ok {
		return rf(teamID, channelName)
	}
	if rf, ok := ret.Get(0).(func(string, string) *model.Channel); ok {
		r0 = rf(teamID, channelName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) *model.AppError); ok {
		r1 = rf(teamID, channelName)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.AppError)
		}
	}

	return r0, r1
}

// MockChannelRepo_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockChannelRepo_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - teamID string
//   - channelName string
func (_e *MockChannelRepo_Expecter) GetByName(teamID interface{}, channelName interface{}) *MockChannelRepo_GetByName_Call {
	return &MockChannelRepo_GetByName_Call{Call: _e.mock.On("GetByName", teamID, channelName)}
}

func (_c *MockChannelRepo_GetByName_Call) Run(run func(teamID string, channelName string)) *MockChannelRepo_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockChannelRepo_GetByName_Call) Return(_a0 *model.Channel, _a1 *model.AppError) *MockChannelRepo_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChannelRepo_GetByName_Call) RunAndReturn(run func(string, string) (*model.Channel, *model.AppError)) *MockChannelRepo_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetDirect provides a mock function with given fields: userID
func (_m *MockChannelRepo) GetDirect(userID string) (*model.Channel, *model.AppError) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDirect")
	}

	var r0 *model.Channel
	var r1 *model.AppError
	if rf, ok := ret.Get(0).(func(string) (*model.Channel, *model.AppError)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) *model.Channel); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *model.AppError); ok {
		r1 = rf(userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.AppError)
		}
	}

	return r0, r1
}

// MockChannelRepo_GetDirect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDirect'
type MockChannelRepo_GetDirect_Call struct {
	*mock.Call
}

// GetDirect is a helper method to define mock.On call
//   - userID string
func (_e *MockChannelRepo_Expecter) GetDirect(userID interface{}) *MockChannelRepo_GetDirect_Call {
	return &MockChannelRepo_GetDirect_Call{Call: _e.mock.On("GetDirect", userID)}
}

func (_c *MockChannelRepo_GetDirect_Call) Run(run func(userID string)) *MockChannelRepo_GetDirect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockChannelRepo_GetDirect_Call) Return(_a0 *model.Channel, _a1 *model.AppError) *MockChannelRepo_GetDirect_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChannelRepo_GetDirect_Call) RunAndReturn(run func(string) (*model.Channel, *model.AppError)) *MockChannelRepo_GetDirect_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChannelRepo creates a new instance of MockChannelRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChannelRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChannelRepo {
	mock := &MockChannelRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
