// Code generated by mockery v2.52.2. DO NOT EDIT.

package usecase

import (
	model "github.com/evrone-erp/mattermost-plugin-welcomebot/server/internal/model"
	publicmodel "github.com/mattermost/mattermost/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// MockTeamWelcomeRepo is an autogenerated mock type for the TeamWelcomeRepo type
type MockTeamWelcomeRepo struct {
	mock.Mock
}

type MockTeamWelcomeRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamWelcomeRepo) EXPECT() *MockTeamWelcomeRepo_Expecter {
	return &MockTeamWelcomeRepo_Expecter{mock: &_m.Mock}
}

// GetTeamWelcome provides a mock function with given fields: teamID
func (_m *MockTeamWelcomeRepo) GetTeamWelcome(teamID string) (*model.TeamWelcome, *publicmodel.AppError) {
	ret := _m.Called(teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamWelcome")
	}

	var r0 *model.TeamWelcome
	var r1 *publicmodel.AppError
	if rf, ok := ret.Get(0).(func(string) (*model.TeamWelcome, *publicmodel.AppError)); ok {
		return rf(teamID)
	}
	if rf, ok := ret.Get(0).(func(string) *model.TeamWelcome); ok {
		r0 = rf(teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TeamWelcome)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *publicmodel.AppError); ok {
		r1 = rf(teamID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*publicmodel.AppError)
		}
	}

	return r0, r1
}

// MockTeamWelcomeRepo_GetTeamWelcome_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamWelcome'
type MockTeamWelcomeRepo_GetTeamWelcome_Call struct {
	*mock.Call
}

// GetTeamWelcome is a helper method to define mock.On call
//   - teamID string
func (_e *MockTeamWelcomeRepo_Expecter) GetTeamWelcome(teamID interface{}) *MockTeamWelcomeRepo_GetTeamWelcome_Call {
	return &MockTeamWelcomeRepo_GetTeamWelcome_Call{Call: _e.mock.On("GetTeamWelcome", teamID)}
}

func (_c *MockTeamWelcomeRepo_GetTeamWelcome_Call) Run(run func(teamID string)) *MockTeamWelcomeRepo_GetTeamWelcome_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTeamWelcomeRepo_GetTeamWelcome_Call) Return(_a0 *model.TeamWelcome, _a1 *publicmodel.AppError) *MockTeamWelcomeRepo_GetTeamWelcome_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamWelcomeRepo_GetTeamWelcome_Call) RunAndReturn(run func(string) (*model.TeamWelcome, *publicmodel.AppError)) *MockTeamWelcomeRepo_GetTeamWelcome_Call {
	_c.Call.Return(run)
	return _c
}

// SetTeamWelcome provides a mock function with given fields: teamID, tw
func (_m *MockTeamWelcomeRepo) SetTeamWelcome(teamID string, tw *model.TeamWelcome) *publicmodel.AppError {
	ret := _m.Called(teamID, tw)

	if len(ret) == 0 {
		panic("no return value specified for SetTeamWelcome")
	}

	var r0 *publicmodel.AppError
	if rf, ok := ret.Get(0).(func(string, *model.TeamWelcome) *publicmodel.AppError); ok {
		r0 = rf(teamID, tw)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*publicmodel.AppError)
		}
	}

	return r0
}

// MockTeamWelcomeRepo_SetTeamWelcome_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTeamWelcome'
type MockTeamWelcomeRepo_SetTeamWelcome_Call struct {
	*mock.Call
}

// SetTeamWelcome is a helper method to define mock.On call
//   - teamID string
//   - tw *model.TeamWelcome
func (_e *MockTeamWelcomeRepo_Expecter) SetTeamWelcome(teamID interface{}, tw interface{}) *MockTeamWelcomeRepo_SetTeamWelcome_Call {
	return &MockTeamWelcomeRepo_SetTeamWelcome_Call{Call: _e.mock.On("SetTeamWelcome", teamID, tw)}
}

func (_c *MockTeamWelcomeRepo_SetTeamWelcome_Call) Run(run func(teamID string, tw *model.TeamWelcome)) *MockTeamWelcomeRepo_SetTeamWelcome_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*model.TeamWelcome))
	})
	return _c
}

func (_c *MockTeamWelcomeRepo_SetTeamWelcome_Call) Return(_a0 *publicmodel.AppError) *MockTeamWelcomeRepo_SetTeamWelcome_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamWelcomeRepo_SetTeamWelcome_Call) RunAndReturn(run func(string, *model.TeamWelcome) *publicmodel.AppError) *MockTeamWelcomeRepo_SetTeamWelcome_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamWelcomeRepo creates a new instance of MockTeamWelcomeRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamWelcomeRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamWelcomeRepo {
	mock := &MockTeamWelcomeRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
