name: CI
on: pull_request

jobs:
  tests:
    name: runner / tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.6
      - name: environment
        run: |
          make apply
      - name: Unit Tests
        run: |
          go test -v ./server/...

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.6
      - name: environment
        run: |
          make apply
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.4
